# Generated by Django 4.0.3 on 2022-04-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_added',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
