# Generated by Django 4.0.3 on 2022-04-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
